In [8]:
import pandas as pd

df = pd.read_csv("../data/raw/test.csv", encoding='cp932')

print("=== shape ===")
print(df.shape)

print("\n=== dtypes ===")
print(df.dtypes)

print("\n=== head(10) ===")
df.head(10)

=== shape ===
(550, 1558)

=== dtypes ===
sample number       int64
species number      int64
樹種                 object
9993.76781        float64
9989.9107         float64
                   ...
4015.24982        float64
4011.39271        float64
4007.5356         float64
4003.6785         float64
3999.82139        float64
Length: 1558, dtype: object

=== head(10) ===

,sample number,species number,樹種,9993.76781,9989.9107,9986.05359,9982.19648,9978.33937,9974.48227,9970.62516,...,4034.53536,4030.67826,4026.82115,4022.96404,4019.10693,4015.24982,4011.39271,4007.5356,4003.6785,3999.82139
0,95,2,クスノキ,0.32877,0.32855,0.32823,0.32792,0.32759,0.32729,0.32713,...,1.35443,1.36345,1.36470,1.36110,1.35863,1.35918,1.36074,1.35224,1.33495,1.32482
1,96,2,クスノキ,0.30061,0.30006,0.29978,0.29984,0.29977,0.29945,0.29914,...,1.12196,1.12506,1.12357,1.11911,1.11655,1.11955,1.12671,1.13182,1.13070,1.12377
2,97,2,クスノキ,0.26048,0.26033,0.26000,0.25970,0.25952,0.25945,0.25927,...,0.98370,0.98904,0.99325,0.99610,0.99886,0.99919,0.99367,0.98723,0.98868,0.99461
3,98,2,クスノキ,0.23210,0.23188,0.23167,0.23158,0.23142,0.23122,0.23119,...,0.93830,0.94524,0.94897,0.95018,0.95243,0.95574,0.95703,0.95530,0.95444,0.95832
4,99,2,クスノキ,0.19725,0.19704,0.19687,0.19676,0.19660,0.19644,0.19639,...,0.87793,0.88175,0.88647,0.89267,0.89790,0.90191,0.90292,0.90119,0.89835,0.89623
5,100,2,クスノキ,0.16636,0.16604,0.16575,0.16569,0.16571,0.16566,0.16553,...,0.83313,0.83622,0.84134,0.84628,0.85040,0.85423,0.85665,0.86091,0.86792,0.86981
6,101,2,クスノキ,0.13970,0.13952,0.13944,0.13943,0.13934,0.13922,0.13912,...,0.80197,0.80521,0.80593,0.81046,0.81877,0.82378,0.82284,0.81957,0.81843,0.81755
7,102,2,クスノキ,0.12052,0.12034,0.12016,0.12003,0.11986,0.11975,0.11975,...,0.78793,0.79100,0.79217,0.79215,0.79441,0.79899,0.80142,0.80269,0.80558,0.80263
8,103,2,クスノキ,0.10383,0.10359,0.10342,0.10341,0.10338,0.10329,0.10316,...,0.77014,0.77202,0.77487,0.77903,0.78391,0.78885,0.78970,0.78470,0.77929,0.77631
9,104,2,クスノキ,0.09005,0.08990,0.08988,0.08988,0.08975,0.08960,0.08956,...,0.76183,0.76414,0.76752,0.76888,0.76860,0.77145,0.77832,0.78480,0.78772,0.78900

In [9]:
# 各樹種ごとのレコード数
record_counts = df.groupby('樹種')['sample number'].count().reset_index()
record_counts.columns = ['樹種', 'レコード数']
record_counts = record_counts.sort_values('レコード数', ascending=False).reset_index(drop=True)
print(f"樹種数: {len(record_counts)}")
record_counts

樹種数: 6

      樹種  レコード数
0     スギ    192
1    チーク    101
2   クスノキ     96
3    ケヤキ     63
4  ヤマザクラ     53
5     タモ     45